export const GET_CAMERAS_INIT = 'GET_CAMERAS_INIT';
export const GET_CAMERAS_SUCCESS = 'GET_CAMERAS_SUCCESS';
export const GET_CAMERAS_FAIL = 'GET_CAMERAS_FAIL';

export const GET_CAMERA_INIT = 'GET_CAMERA_INIT';
export const GET_CAMERA_SUCCESS = 'GET_CAMERA_SUCCESS';
export const GET_CAMERA_FAIL = 'GET_CAMERA_FAIL';

export const STORE_CAMERA_INIT = 'STORE_CAMERA_INIT';
export const STORE_CAMERA_SUCCESS = 'STORE_CAMERA_SUCCESS';
export const STORE_CAMERA_FAIL = 'STORE_CAMERA_FAIL';

export const DELETE_CAMERA_INIT = 'DELETE_CAMERA_INIT';
export const DELETE_CAMERA_SUCCESS = 'DELETE_CAMERA_SUCCESS';
export const DELETE_CAMERA_FAIL = 'DELETE_CAMERA_FAIL';
